### ISSUE TITLE
Test if db contains columns for style file

### ISSUE THREAD

**Issue by gravitystorm** [openstreetmap/osm2pgsql#108]
It would be useful if you could do something like `osm2pgsql --test-style foo.style` which then examines an existing database and lets you know if it contains all the columns required by that style, or whether you need to reload the database.

**Comment by pnorman** [comment]
I'm leaning against this because it's a niche use case, and doesn't really solve the problem. A style file and import settings can change in ways that don't change the column definitions. In fact, I've found this more common - importing with one set of command line flags, then using a different one for updates.

**Comment by lonvia** [comment]
This could also be done in a simple external script (as part of this repo or not). I'd prefer that over adding the feature into osm2pgsql directly.
