### ISSUE TITLE
Flex backend: hstore column for all flex tables

### ISSUE THREAD

**Issue by mboeringa** [openstreetmap/osm2pgsql#1109]
Thinking about the flex backend and its usage, one thing that struck me as likely being missing in the current setup (correct me if I am wrong, I haven't attempted to use it yet!), is an hstore column on all generated flex backend custom tables.

While I appreciate that you can define the columns through Lua scripts, adding an hstore column to each dedicated table, adds a significant benefit and flexibility otherwise not easily achieved: the ability to customize a table's columns in a SQL statement via creation of (temporary) views that extract extra columns from hstore via the PostgreSQL hstore syntax.

This has the advantage that you can manage table contents through SQL instead of having to hack into Lua scripts, and thus adds another level of "flexibility" to the use of the flex backend.

E.g. I could well see an organization like HOT adding a custom table for hospitals, and then create custom views on it with dedicated information based on hstore extracted specific attributes for a region or project, that are not defined in Lua.

**Comment by joto** [comment]
If you want to have an hstore column on a table then the flex backend allows you to do that. If you don't want one, then don't configure one. It couldn't be more flexible than this.

**Comment by mboeringa** [comment]
@joto , while I appreciate this, @gravitystorm already pointed out that configuration through Lua is more akin to programming, than basic database / SQL management (https://github.com/gravitystorm/openstreetmap-carto/issues/4112#issuecomment-610249371).

We should not forget that there may be lot of users who just manage to get by with a basic knowledge of SQL, but aren't skilled in real programming.

Having an hstore column _by default_ on all flex tables, would be of great help to that group of users, and would avoid the need to dig into Lua scripts.

I fear we may be losing ease of use in favor of flexibility.

**Comment by lonvia** [comment]
I don't follow. I thought your argument was to get more flexibility on the SQL side. I think it is save to assume that people who are able to formulate complicated SQL queries over hstore columns are able to change a Lua script to add a hstore column.

If the argument is ease-of-use, then there is always the C transform, which includes the hstore capability. We have no plans to retire the simple C transform. It might morph into a pre-written Lua script file but that would be a mere implementation detail. The user-side-facing behaviour as is not going to change. You can use this if you are uncomfortable with Lua.

We are surely not going to add lots of behaviour-changing switches to the flex backend if the same behaviour can easily be achieved by adding a minimal amount of Lua code. The goal was to get away from those switches because they are difficult to understand and tend to have badly specified side effects on each other.

**Comment by mboeringa** [comment]
> I think it is save to assume that people who are able to formulate complicated SQL queries over hstore columns are able to change a Lua script to add a hstore column.

I think this is a bit to much looked on it from skilled programmer's perspective. There are _many_ people, e.g. in government agencies using something like QGIS, who only have some basic knowledge of SQL, but aren't really versed in programming.

Adding a column to a view based on hstore also doesn't require overly "complicated SQL", it is just

`tags -> 'golf' AS my_golf_field`

based on the current 'tags' name of the hstore column in a 'openstreetmap-carto' / osm2pgsql import.

I still think having an hstore column by default would benefit a lot of users just accessing the data from a simple database / data store perspective, and that aren't interested in building their own custom style, but just want to use the output of the default 'openstreetmap-carto' or some other style.

**Comment by joto** [comment]
There is no way we are going to force a column on all users. That adds overhead for all those who don't want it. And it doesn't solve your problem anyway, because the column would still have to be filled, and there is no sensible way to come up with a default fill for that column. Please try out the flex backend and learn how it is supposed to work and you will see that it doesn't make sense to have this required column.

Osm2psgql has had "opinions" on what the database should look like for too long a time. We are not going back to that. The flex backend config is much simpler and much easier to understand than the old setup *because* it doesn't force anything on you. It simply says: You decide what you want and then osm2pgsql makes it work. 

What does make sense is to have simple default or example configurations that people who don't want to delve into the details can use.

**Comment by mboeringa** [comment]
> Osm2psgql has had "opinions" on what the database should look like for too long a time.

@joto, I fail to see how adding the hstore column dictates how the "database should look". I am not suggesting adding dozens of custom columns to X tables, instead I just suggest adding the hstore column because it gives access to the **full tagging information associated with a specific object**. 

This is something completely different then "opinons" about how the structure of tables and columns of the Lua defined flex backend should look, because I fully second that isn't sensible.

The hstore column though, is one exception, due to it giving specific access to the full tagging information.


> What does make sense is to have **simple default or example configurations** that people who don't want to delve into the details can use.

This is precisely why I suggest adding - only! - the hstore column by default.

**Comment by gravitystorm** [comment]
> What does make sense is to have simple default or example configurations that people who don't want to delve into the details can use.

Yep, I agree with this. My warning over on the other issue is only aimed at people who want to be a pioneer and who are thinking about developing their own lua files. 

But I expect that most people will either use one of the examples included with osm2pgsql, or from other sources like openstreetmap-carto, and won't want to or need to develop their own. So rather than having a default hstore column, or other choices like that made in the flex backend, I think the better option is having an example configuration (like compatible.lua) that can be used off the shelf instead.

**Comment by gravitystorm** [comment]
> This is something completely different then "opinons" about how the structure of tables and columns of the Lua defined flex backend should look, because I fully second that isn't sensible.

But it *is* a strong opinion on how the table should look. Many tables won't need it. Even the current osm2pgsql has multiple ideas of what should be in an hstore column (--hstore vs --hstore-all) and they both have advantages and disadvantages.

**Comment by mboeringa** [comment]
> because the column would still have to be filled, **and there is no sensible way to come up with a default fill for that column**

@joto, as @gravitystorm pointed out, there is already a couple of options in the current osm2pgsql, so I don't completely understand your remark, unless it refers to complex tag transfers involving relations.

Personally though, I would be fine with the option **--hstore** only, because that option inserts minimal tagging information in the hstore column, thus minimizing storage overhead, while maintaining the full tagging information in combination with the non-hstore ordinary columns.

> But it _is_ a strong opinion on how the table should look. Many tables won't need it.

I hope it is still allowed to have an opinion here ;-)

As to "many tables won't need it": this still is looking from the limited perspective of the style developer itself. Any downstream data user may actually desire to have access to other tag information, while still not wanting to develop their own style. 

There is more uses to the current 'openstreetmap-carto' or other style driven databases than just rendering tiles for the web.

**Comment by lonvia** [comment]
The requested feature can be implemented with the current flex backend already.

Closing the discussion here.

**Comment by mboeringa** [comment]
That's fine, but I do have a few questions then:

- The [docs regarding the flex backend](https://github.com/openstreetmap/osm2pgsql/blob/master/docs/flex.md) show an example of adding an hstore column, but @joto says _"there is no sensible way to come up with a default fill"_. So what does this option do?

> -- definition of the table:
table_pois = osm2pgsql.define_node_table('pois', {
    { column = 'tags', type = 'hstore' },
    { column = 'name', type = 'text' },
    { column = 'geom', type = 'point' },
})

- Is the hstore column being indexed?
- More general, is any indexing taken care of in the flex backend, e.g. at the very least the geometry columns? I don't see anything mentioned about this in the documentation.

Thanks for any info you can share.

**Comment by mboeringa** [comment]
Relevant: https://github.com/openstreetmap/osm2pgsql/issues/1123

**Comment by mboeringa** [comment]
Also related: https://github.com/gravitystorm/openstreetmap-carto/issues/4112#issuecomment-619649864

And: https://github.com/gravitystorm/openstreetmap-carto/tree/flex/master as a flex backend configuration replicating current 4 table setup (planet_osm_polygon/line/points/roads) setup including a hstore column defined on the tables.
