### ISSUE TITLE
Deleted place name persists on the map

### ISSUE THREAD

**Issue by Andrew-Hain** [openstreetmap/osm2pgsql#1116]
A place name [deleted from the map two weeks ago](https://www.openstreetmap.org/node/7312824267/history#map=16/51.4535/-0.3352) remains on the Standard, Cycle Map and Humanitarian layers.

**Comment by SomeoneElseOSM** [comment]
It's getting displayed from https://www.openstreetmap.org/node/7346935180/history I suspect.

**Comment by lonvia** [comment]
This is really not the right place to report map issues. There are a multitude of reasons why the place might be shown and only the operators of the maps can da an appropriate analysis of the database to find out who is at fault. So please report it with them. If they find that the problem is with osm2pgsql, they can still open an issue here with more detailed information.
