### ISSUE TITLE
failed: ERROR:  duplicate key value violates unique constraint "planet_osm_nodes_pkey"

### ISSUE THREAD

**Issue by pcarabasu** [openstreetmap/osm2pgsql#1272]
<EDIT>
I am importing a new country (turkey) to a previously added map (a merged map of 6 other countries, which is working). 
I cleaned the new map (turkey) of the elements it might have in common with the previously added map. Then I tried to add it.
This is how I cleaned it:
osmconvert new_region.pbf -o=new_region.o5m
osmconvert already_loaded_map.pbf -o=already_loaded_map.o5m
osmconvert new_region.o5m --subtract already_loaded_map.o5m -o=new_region_cleaned.o5m
osmconvert new_region_cleaned.o5m -o=new_region_cleaned.pbf
</EDIT>
It all ran well until the end when I got a database connection error due to too many connections. I was running the append with 16 processes. I ran the command again with 8 processes and I ran into this current error.
What should I do now?

Error details:

Reading in file: /home/maprenderer/data/turkey-latest-cleaned.osm.pbf
Processing: Node(48730k 870.2k/s) Way(26k 8.67k/s) Relation(0 0.00/s)COPY_END for COPY planet_osm_nodes FROM STDIN;
 failed: ERROR:  duplicate key value violates unique constraint "planet_osm_nodes_pkey"
DETAIL:  Key (id)=(14455442) already exists.
CONTEXT:  COPY planet_osm_nodes, line 1

**Comment by joto** [comment]
I can't really follow your problem description, but it sounds like you are importing two extracts into the same database. This will fail if there is some overlap between the two extracts, i.e. if there is one node, way, or relation in both input files (in your case node 14455442 is already in the database). The only way to solve this is to merge all input files into one (using [`osmium merge`](https://docs.osmcode.org/osmium/latest/osmium-merge.html) for instance), start with an empty database, and import all data in one go.

Make sure that the input files you are merging are from the exact same point in time, otherwise the merge will not work correctly.

**Comment by pcarabasu** [comment]
I was wondering if I can do something without emptying the database.
I am not importing two extracts. I edited the original description to better explain what I did.

**Comment by joto** [comment]
Sorry, no. When something fails during initial import or update we don't know in which state the database is. A clean reimport is the only way to get to a defined state again.
