### ISSUE TITLE
recursion limit of 1024 exceeded, use -L<N> to change it

### ISSUE THREAD

**Issue by itavy** [openstreetmap/osm2pgsql#13]
i have a problem when trying to compile unde Centos 6.3:

$ ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
/usr/bin/m4:configure.ac:37: recursion limit of 1024 exceeded, use -L<N> to change it
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: autom4te failed with exit status: 1
autoreconf: aclocal failed with exit status: 1

$ uname -rvmpio
2.6.32-279.19.1.el6.x86_64 #1 SMP Wed Dec 19 07:05:20 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

$ aclocal --version
aclocal (GNU automake) 1.11.1

$ autoconf --version
autoconf (GNU Autoconf) 2.63

$ m4 --version
m4 (GNU M4) 1.4.13

below there are the required libraries installed

$ rpm -qa | grep -i boost
boost-date-time-1.41.0-11.el6_1.2.x86_64
boost-wave-1.41.0-11.el6_1.2.x86_64
boost-test-1.41.0-11.el6_1.2.x86_64
boost-thread-1.41.0-11.el6_1.2.x86_64
boost-filesystem-1.41.0-11.el6_1.2.x86_64
boost-graph-1.41.0-11.el6_1.2.x86_64
boost-python-1.41.0-11.el6_1.2.x86_64
boost-serialization-1.41.0-11.el6_1.2.x86_64
boost-iostreams-1.41.0-11.el6_1.2.x86_64
boost-1.41.0-11.el6_1.2.x86_64
boost-system-1.41.0-11.el6_1.2.x86_64
boost-regex-1.41.0-11.el6_1.2.x86_64
boost-signals-1.41.0-11.el6_1.2.x86_64
boost-program-options-1.41.0-11.el6_1.2.x86_64
boost-devel-1.41.0-11.el6_1.2.x86_64

$ rpm -qa | grep libxml
libxml2-devel-2.7.6-8.el6_3.4.x86_64
libxml2-2.7.6-8.el6_3.4.x86_64

$ rpm -qa | grep proj
proj-4.8.0-2.rhel6.x86_64
proj-devel-4.8.0-2.rhel6.x86_64

$ rpm -qa | grep geos
geos-3.3.6-4.rhel6.x86_64
geos-devel-3.3.6-4.rhel6.x86_64

$ rpm -qa | grep bzip2
bzip2-libs-1.0.5-7.el6_0.x86_64
bzip2-devel-1.0.5-7.el6_0.x86_64
bzip2-1.0.5-7.el6_0.x86_64

$ rpm -qa | grep zlib
zlib-1.2.3-27.el6.x86_64
zlib-devel-1.2.3-27.el6.x86_64

$ rpm -qa | grep postgres
postgresql92-devel-9.2.2-1PGDG.rhel6.x86_64
postgresql92-9.2.2-1PGDG.rhel6.x86_64
postgresql92-server-9.2.2-1PGDG.rhel6.x86_64
postgresql92-libs-9.2.2-1PGDG.rhel6.x86_64
postgresql92-contrib-9.2.2-1PGDG.rhel6.x86_64

$ rpm -qa | grep gis
postgis2_92-2.0.2-1.rhel6.x86_64

$ rpm -qa | grep -i gettext
gettext-devel-0.17-16.el6.x86_64
gettext-0.17-16.el6.x86_64
gettext-libs-0.17-16.el6.x86_64

**Comment by henryseron** [comment]
Hi, I'm installing osm2gsql on centos 6.6 and I have this same problem, how can I fix it? I disabled WARN_ALL macros according to https://github.com/hholzgra/osm2pgsql/commit/f710045953b8f02aeba846ba89749961639ee0c5 but did not work.
Thanks.

**Comment by pnorman** [comment]
> Hi, I'm installing osm2gsql on centos 6.6 and I have this same problem, how can I fix it?

Try doing `git clean -xfd` and disabling the warning macros. If that doesn't fix it, build your own autotools and/or m4, do git clean and instead of running `autogen.sh`, run each command in it individually, making sure to use the new versions.

Once you get autogen.sh working, you will run into problems with a few default versions of requirements that come with Centos 6.

* You need a C++11 compiler. Centos 6 pre-dates C++11, so you'll need an appropriate version of GCC (4.8) or clang (3.4).
* The version of Boost on Centos is similarly ancient
* The version of GEOS included will probably compile, but may produce more errors than a recent version
* If you're running the database server on Centos, you should probably build your on PostgreSQL + PostGIS, as I believe the versions of both that come with Centos 6 are end of life
* The Protocol Buffers version is probably too old too

Something called "devtoolset-2" may help with some components.

If using a RPM based distribution, I **strongly** recommend Fedora, or if you need Centos, Centos 7 might be recent enough to avoid some of this work.

If you must use Centos 6, it is possible to compile recent versions of what you need, and osm2pgsql should work then. This is actually not much additional burden, because if you're using Centos you will need to do this anyways for the dependencies of virtually every other component of a tile rendering server.

**Comment by pnorman** [comment]
You might also find 0.86.0 easier to work with as its the old C version.

**Comment by henryseron** [comment]
Thanks pnorman for your help, it was so helpful. I followed your advise and then I can ran autogen.sh without warnings or error.

Thanks a lot.
