### ISSUE TITLE
admin_centre role is not imported

### ISSUE THREAD

**Issue by SL-philippebisotto** [openstreetmap/osm2pgsql#1422]
Hello,

When i import data from osm file, i can't select the admin centre place inside an administrative boundary polygon.
Cause the admin_center role of the node is not imported.

<img width="716" alt="AdminCenter" src="https://user-images.githubusercontent.com/60103650/108733611-f5efa200-752e-11eb-88c4-816a6790b05a.png">

**Comment by lonvia** [comment]
This is intentional. osm2pgsql builds only simple geometries and not collections.

When you can use the flex backend, you can save the node id of an admin centre in an extra column of your boundary relation and then cross-reference the node with that. But you have to create your own custom style for that.
