### ISSUE TITLE
Flex clean_tags in process_relation

### ISSUE THREAD

**Issue by andreynovikov** [openstreetmap/osm2pgsql#1441]
Imho here:
https://github.com/openstreetmap/osm2pgsql/blob/86ad6d6026a17ae2f714f37e4288330b5ee4a01d/flex-config/generic.lua#L251-L255
and in other flex examples it will never return as at least relation has `object.tags.type`. Shouldn't it be something like:
```lua
local type = object:grab_tag('type')
if clean_tags(object.tags) then
    return
end
```

**Comment by joto** [comment]
It shouldn't really matter that much. And while 99.80% of relations have a `type` tag, it is not required. And there are about 60.000 relations in the current planet hat only have a `type` tag. Most of them can probably be ignored, because they don't carry useful information, but what's to say that some `type`s are not enough? So maybe its better to leave it as it is to be on the "safe" side.

The bigger problem with your proposed change is that it removes the `type` tag from the tags hstore field added to the database. So there is some information lost here. We could add it back in, but removing it and then adding it back in also comes with its cost.

**Comment by joto** [comment]
I looked at this again and I now think you are right @andreynovikov . We "split" up the data based on the type onto different tables here and there is no case where the `type` tag will be useful in the database and everything without type is dropped anyway. So I'll change this. Thanks @andreynovikov .
