### ISSUE TITLE
Pass parameters to lua part

### ISSUE THREAD

**Issue by doskabouter** [openstreetmap/osm2pgsql#1520]
--output-pgsql-schema is not passed to the lua part, so each time output should go to a different schema, not only the osm2pgsql command needs to be changed but also the lua script.
Same holds for the various tablespace options

**Comment by joto** [comment]
This is on purpose. We are phasing out the command line options in favour of the config file. We decided in a strict separation between "the old way of doing things" and "the new way" to avoid confusion (what happens if the config file says something different than the command line...). And yes, this is a somewhat painful change, but in the long run it is much clearer.

**Comment by doskabouter** [comment]
ok, i get it

**Comment by lonvia** [comment]
If you have variables in the Lua script that you need to change for every run, the best solution is to work with environment variables.

See also https://osm2pgsql.org/doc/manual.html#accessing-environment-variables-from-lua
