### ISSUE TITLE
Flex creating polygons from inner ways (holes) where outer ways not in dataset

### ISSUE THREAD

**Issue by rouen-sk** [openstreetmap/osm2pgsql#1584]
Using osm2pgsql version 1.5.1 (1.5.1-24-ga50c54e2). 
If you have dataset containing "inner" ways but not "outer" ways for some relations, geometries created for those relations would be incorrect - I believe they are created from the inner ways used as outer ring, so the "hole" becomes the polygon itself. 

Example: Vatican city is "hole" in multiple italian administrative relations. If you try to import `boundary=administrative` relations from vatican extract (attached) into table with column `geom = { create = 'area' }`  you will get multiple Italian relations with the same geometry of vatican city (i.e. osm relations ids 41313, 41485, 40784, 365331)

```
function osm2pgsql.process_relation(object)
	-- osm_admin_area (polygons)
	if object.tags.boundary=='administrative' 
	then	
        tables.osm_admin_area:add_row({
	    iso_code = object.tags['ISO3166-1:alpha3'],
	    admin_level = object.tags.admin_level,
	    name = object.tags.name,
            tags = object.tags,
            geom = { create = 'area' }
        })		
	end
end
```
[vatican-city.osm.zip](https://github.com/openstreetmap/osm2pgsql/files/7625196/vatican-city.osm.zip)

**Comment by rouen-sk** [comment]
Thanks for response and thoughts. I did not try other outputs, I am using only flex, so I specified that just to be clear. 

I see why this is problematic, and there probably isn't one fits all solution. I can totally imagine people being confused why their polygon of France is missing, just because relation of France containts also small islands in carribean. Maybe the best solution would be some "strict mode" switch - when enabled, relations for which there are not all members present are ignored (not imported at all).

**Comment by lonvia** [comment]
If we drop incomplete relations, then Europe extracts will suddenly miss the countries of [France](https://www.openstreetmap.org/relation/2202162) and [the Netherlands](https://www.openstreetmap.org/relation/2323309).

**Comment by joto** [comment]
Adding a "strict" mode would be possible, but it would probably not be very helpful in practice, because most users will not need it and those that do will probably not know that there is this magic option which might fix that problem and probably give you others instead. We thought about giving you the information in the flex config file for each geometry, whether it was derived from complete data or not which would allow you to dynamically decide which things to import and which not. But that is a lot of work for something obscure that will not happen often. It is unlikely people will use that feature or even understand the repercussions. So unfortunately this is something we will not fix unless somebody has some great idea how to do so.

I have [added some information to the documentation](https://osm2pgsql.org/doc/manual.html#handling-of-incomplete-osm-data).

In your case you might be able to download the complete relation creating the problem and merging the OSM data of your extract with that data before import. Or you simply add a check in your flex config file for that one relation and not import it.

**Comment by rouen-sk** [comment]
Thanks for considering it, I understand your decision. Maybe I will try to fix it and create pull request later. For now, I can use workaround that works for my use case (I detect and delete areas created from relations, for which not all ways are present - since I import also ways and relation_members tables).
