### ISSUE TITLE
More recent version than 1.2.1 on Ubuntu 20.04?

### ISSUE THREAD

**Issue by iboates** [openstreetmap/osm2pgsql#1591]
Are there any plans to release a more recent version than 1.2.1 on Ubuntu 20.04?

20.04 is the current LTS for Ubuntu and I am version locked there, but I would like to take advantage of some of the newer features.

**Comment by joto** [comment]
That's not up to us, we are not the maintainers of those distributions. Usually there are no newer versions of any software for stable distribution releases, because, well, they are supposed to be stable. You might be able to use packages from [Debian Backports](https://backports.debian.org/) which might or might not be compatible with Ubuntu. Use at your own risk.

Or you can always compile a new version yourself.
