### ISSUE TITLE
Allow method of specifying custom partial indexes

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#166]
It would be useful to be able to specify a list of custom indexes, which could be created at import time. This would require a few things
- A syntax for specifying the index, predicate, and where clauses
- An overhaul of the existing index creation code, probably creating all indexes like the custom indexes
- Limiting the parallelism during index creations, either to `--number-processes` or a different value, to account for the case where the database has different parallelism than the osm2pgsql machine.
  - Indexes on _ways, _polygon and _line should be created first, in that order, for job scheduling reasons.

**Comment by thbeutin** [comment]
I would prefer an option to skip the whole indexing and data aligning procedure at all. This could speed my process a lot since i have to do statistics on tags, so i have to reindex the whole database anyway.

What if there would be a default sql file which is read by osm2pgsql after inserting the data, so the experienced user can fit this to his/her needs?

**Comment by pnorman** [comment]
Closing in favour of #27. There are [scripts](https://github.com/gravitystorm/openstreetmap-carto/blob/master/scripts/indexes.py) that will generate custom indexes from a YAML file, optionally including default osm2pgsql indexes.
