### ISSUE TITLE
how to update osm2pgsql to v .1.7.0

### ISSUE THREAD

**Issue by toqeer786** [openstreetmap/osm2pgsql#1807]
i want to update my osm2pgsql to latest version 
currently i am using
osm2pgsql version 1.2.1 (64 bit id space)
whenever i run the command 
:sudo apt install osm2pgsql-1.7.0
i have the follwoing error 

E:Unable to locate package osm2pgsql-1.7.0
E: Couldn't find any package by glob 'osm2pgsql-1.7.0
i also try to upgrade the current version t0 v1.7.0 but it wasnt successfull

i am using ubuntu 20.04 and postgresql  v12

**Comment by joto** [comment]
This isn't specific to osm2pgsql. Ubuntu (like most Linux distributions) generally doesn't supply updates to newer versions of programs unless there are security problems. You have to update your Ubuntu version to get new versions of the programs supplied with Ubuntu. So you should update your Ubuntu at some point. But the newest Ubuntu will also not give you the newest osm2pgsql, so that's of limited help.

You'll probably have to compile osm2pgsql yourself. See https://osm2pgsql.org/doc/install.html for instructions.
