### ISSUE TITLE
Import crashes with new GeoHash

### ISSUE THREAD

**Issue by it-solutions-zehaczek** [openstreetmap/osm2pgsql#265]
Hi,

i just tried an import using 0.87.2-dev on postgres 9.1 with enabled slim-mode, hstore and flatnodes and got the following error:
CREATE TABLE planet_osm_polygon_tmp AS SELECT * FROM planet_osm_polygon ORDER BY ST_GeoHash(ST_Transform(ST_Envelope(way),4326),10) failed: ERROR: ST_GeoHash: lwgeom_geohash returned NULL.

A switchback to 0.87.1 solves the problem.

It seems to depend on the data. Planet, Germany and Hesse crashed. Some other smaller areas passed without error. So you best test with Hesse file if you like to reproduce the error (http://download.geofabrik.de/europe/germany/hessen.html).

Regards,
Chris

**Comment by pnorman** [comment]
Given this works with the planet and 9.1 across multiple systems, to reproduce we need your full postgis version details (`select postgis_full_version();`) and **exactly* which file you imported to produce the error.

**Comment by it-solutions-zehaczek** [comment]
select postgis_full_version() 
=> POSTGIS="1.5.3" GEOS="3.3.3-CAPI-1.7.4" PROJ="Rel. 4.7.1, 23 September 2009" LIBXML="2.7.8" USE_STATS

Tried these files:
http://planet.openstreetmap.org/pbf/planet-latest.osm.pbf
http://download.geofabrik.de/europe/germany/hessen-latest.osm.pbf

**Comment by pnorman** [comment]
> select postgis_full_version() 
> => POSTGIS="1.5.3" GEOS="3.3.3-CAPI-1.7.4" PROJ="Rel. 4.7.1, 23 September 2009" LIBXML="2.7.8" USE_STATS

I don't know if I have any machines still with PostGIS 1.5, as it's not recommended for performance reasons.

> Tried these files:
> http://planet.openstreetmap.org/pbf/planet-latest.osm.pbf
> http://download.geofabrik.de/europe/germany/hessen-latest.osm.pbf

The -latest files are continually changing. I could probably figure out which planet-latest since that changes weekly, but the -latest geofabrik files change daily. I'll have a go.

**Comment by it-solutions-zehaczek** [comment]
It doesn't matter that the files are updated daily. Pick one and it will crash.
Maybe you should flag 0.87.1 as the latest version that is compatible with postgis 1.5 then.

**Comment by pnorman** [comment]
> Maybe you should flag 0.87.1 as the latest version that is compatible with postgis 1.5 then.

I've done plenty of ORDER BY ST_GeoHash on 1.5, so I don't see why it would be the cause.

**Comment by lonvia** [comment]
I managed to reproduce that error on my system with postgis 1.5 and geos 3.4. The culprit is this relation: https://www.openstreetmap.org/relation/3726445 It creates two objects:

~~~
gis=# SELECT st_astext(way) FROM planet_osm_polygon where osm_id = -3726445;
               
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 GEOMETRYCOLLECTION EMPTY
 POLYGON((962706.44 6542771.51,962706.53 6542771.96,962707.82 6542778.8,962709.81 6542789.77,962710.24 6542791.55,962725.24 6542788.71,962722.44 6542773.87,962716.21 6542775.05,962715.23 6542769.84,962709.3 6542770.97,962706.44 6542771.51))
(2 rows)
~~~

That trips the GeoHash function.

Now, the interesting question is what that empty geometry collection is doing there.

**Comment by lonvia** [comment]
See #291 for a fix of the GeoHash error. I've opened a separate issue for the empty geometry bug at #292.
