### ISSUE TITLE
Very low performace on adding diff-s

### ISSUE THREAD

**Issue by jendrusk** [openstreetmap/osm2pgsql#343]
I'm having some trouble with adding diffs generated by osmosis and appreciate any help...

My first import was on good performance:

Processing: Node(1298k 14.9k/s) Way(148k 0.90k/s) Relation(6747 137.69/s)  parse time: 301s

But next which start 10 minutes after this one ended (and all after it) is in very low performance:

Processing: Node(1052k 0.4k/s) Way(137k 0.11k/s) Relation(4134 60.79/s)  parse time: 3652s

What is most confusing - I didn't change any of database parameters, there was no database restart between them and seems like nothing have changed in enviroment (or I forgot sth).

Maybe someone know this problem or have any idea what is causing it ?
Maybe there is some way to debug it (except working on code - I'm not developer) ?

Any help appreciated (ple, ple, pleeeezzzzzz)

PS. I fallowed the issue #163 with large shared buffers and there is little better but still far from first run:

Processing: Node(198k 1.2k/s) Way(15k 0.31k/s) Relation(406 81.20/s)  parse time: 220s

PS2 I analysed replication logs and found that not every import is that slow - I've got some imports (at night) running with normal performace. Between first and second run I've launched Geoserver which is using this data (Tables planet_osm_* via some views). Pottencialy it is possible that lots of selects on this data will cause slowing down updates, but I made test - turn off geoserver and run osm2pgsql and there was no change performace... (or I'm wrong and tests was not well-made??)

**Comment by pnorman** [comment]
How many hours of diffs did you consume at once?

**Comment by jendrusk** [comment]
Hi pnorman - Thanks for the answer.
on first imports it was 12h, when I saw it is running for 12 hours I decided to shorten this time to 1h, after changing shared_buffers I changed to 2h... Unfortunately, I do not see any relationship between the size of the package and performance of processing nodes.

You can see full log here:

http://mapa.abakus.net.pl/logs/replication.log

Don't matter the '---start' parts - it's another instance of script attempting to run, but it can't because one is already running.

**Comment by pnorman** [comment]
Processing node times are probably the easiest to look at, as it's one of the simplest stages. With `--number-processes 2 -v -G -K -j -x -s --append` it's going to be writing the node info to the nodes table and some of those into the points table.

`-x -j` is interesting, because I recall reports of that combination being very slow since it was writing full details of every node into the points table (-x adding tags, and -j putting them into hstore). But it wouldn't cause run to run variations.

None of this really helps identify the cause of the variations, and the log doesn't provide enough information.

Do you have logging (nagios, munin, etc) for the first two runs?

**Comment by jendrusk** [comment]
I've  sended link to munin to Your e-mail (penorman@mac.com) :)

**Comment by pnorman** [comment]
Did some debugging with the reporter at the time - I don't think there's any bugs on the osm2pgsql side.
