### ISSUE TITLE
Rendering of highways, which are included to relations with similar tags

### ISSUE THREAD

**Issue by DinamikGitHub** [openstreetmap/osm2pgsql#430]
this perfectly good road is not rendered for some reason: https://www.openstreetmap.org/way/141673809
![psql01](https://cloud.githubusercontent.com/assets/3268650/9104934/a9c0f8e6-3c1a-11e5-9a5f-e0f755165803.png)
Rendering of this place - data from Overpass, local render with openstretmap-carto style shows no glitches.
![psql2](https://cloud.githubusercontent.com/assets/3268650/9104937/b9098124-3c1a-11e5-9324-4f719fef2ac9.png)
They say in Russian forum that this is a osm2pgsql bug: when all ways have tags that a multipolygon on them has, these ways drop that tag.

Originally posted in https://github.com/gravitystorm/openstreetmap-carto/issues/1722 and https://github.com/openstreetmap/openstreetmap-website/issues/1024

**Comment by pnorman** [comment]
> They say in Russian forum that this is a osm2pgsql bug: when all ways have tags that a multipolygon on them has, these ways drop that tag.

I doubt this is an old-style multipolygon handling bug like #304. As you identified in the bug report, if you load the data and render, it works. If I download the data from the API and load (`osm2pgsql --slim` for ordering), the linestring appears. If I look at my database of Europe from a couple months ago, it has the linestring.

If it's a diff related bug, it's probably #67. If its some other bug, it's not exhibiting itself on current versions.

If you can produce a .osm file which exhibits the problem we can reopen the issue, but otherwise it's resolved
