### ISSUE TITLE
Symbol Lookup Error

### ISSUE THREAD

**Issue by m3rashid** [openstreetmap/osm2pgsql#449]
Some helpful information:

OS: Ubuntu 14.04
osm2pgsql SVN version 0.81.0 (64bit id space)
psql (PostgreSQL) 9.3.9

I get the following error:

Reading in file: planet-latest-september-5.osm.pbf
Processing: Node(3015810k 60.0k/s) Way(0k 0.00k/s) Relation(0 0.00/s)osm2pgsql: symbol lookup error: osm2pgsql: undefined symbol: _ZN4geos4geom10CoordinateD1Ev

**Comment by pnorman** [comment]
0.81.0 is ancient. Please try with at least 0.86.0, or preferably 0.88.1 or later.

**Comment by jburgess777** [comment]
The error is probably due to a mismatch between the geos library used to compile osm2pgsql and the one version the linker loads when you run osm2pgsql. It seems likely you built your own geos library from source and installed in /usr/local/lib but when osm2pgsql runs it uses the one from /usr/lib. Having multiple copies of the same library often causes issues.

You could try "ldd /path/to/osm2pgsql", this will likely confirm it is trying to load the wrong version of the geos library.

The best option is often to uninstall the packaged version of the library and its "dev" package when you intend to compile it yourself.

Alternatively, you might be able to force it to use the right library setting LD_LIBRARY_PATH before running osm2pgsql.
