### ISSUE TITLE
Export change list with single index format

### ISSUE THREAD

**Issue by nyurik** [openstreetmap/osm2pgsql#461]
Instead of x,y tile coordinates, Kartotherian uses [a single index](https://www.mediawiki.org/wiki/Maps/Tile_server_implementation#Tile_ID). Please add an ability to  export changelist in the index format.

**Comment by pnorman** [comment]
This would mean not combining adjacent tiles into a higher level zoom, right?

How does this differ from other Morton codes, Z-order, and quadkeys? I'm specifically interested in quadkeys, since they're already used for serving maps.

See also 
* http://wiki.openstreetmap.org/wiki/QuadTiles
* https://msdn.microsoft.com/en-us/library/bb259689.aspx

**Comment by nyurik** [comment]
Thanks for the links!  I will have to read up on quadtiles/quadkeys.  As for combining, upon further thinking, I don't think its worth the time - its much easier to simply convert (x,y) into a single index, sort by that index, and combine sequential indexes into ranges, thus greatly simplifying tile regeneration. Also, the list should generate just one, high zoom level - because the importer will be able to automatically convert it to the lower zooms as needed.

**Comment by joto** [comment]
I don't think we will create different index formats, because that's something that can be solved outside osm2pgsql with conversion scripts. Closing here, but if something about this should be considered in future expire fuctionality, consider adding it to #1662 .
