### ISSUE TITLE
lat lon changed from osm to db

### ISSUE THREAD

**Issue by lincoln310** [openstreetmap/osm2pgsql#503]
Hi, i create osm from josm, and contains some point like:
  node id='-34423' visible='true' lat='39.11292963103' lon='117.74909839384'
    tag k='bench' v='yes' 

But when i export to postgis db, it changed to 
<pre>
  id   |    lat    |    lon     |    tags     
--------+-----------+------------+-------------
 -34423 | 473786070 | 1310776967 | {bench,yes}
</pre>

How does this happen? And beside the value changed, how to keep 47.3786070 and 39.11292963103 at the same magnitude?

**Comment by lonvia** [comment]
Quoting answer from @woodpeck via mailinglist:

> The data has undergone what is called a "map projection". If you don't
> want that, use the -l (ell) flag on osm2pgsql.

**Comment by pnorman** [comment]
Yes - this is intentional. You're looking at the slim tables, which are used for internal osm2pgsql purposes and store coordinates in the target projection (mercator), after scaling.

For most uses you want to be looking at planet_osm_point, not planet_osm_node, otherwise you're depending on a fairly specific osm2pgsql command line.
