### ISSUE TITLE
Straight line cut in 10 pieces by osm2pgsql and leading to mapnik issues

### ISSUE THREAD

**Issue by damiendevienne** [openstreetmap/osm2pgsql#507]
Hello, 
I had some issue with rendering my data with mapnik and it appears to be related to the way data are stored in the database after import with osm2pgsql. 
I use a very simple example data of 2 nodes and 1 way linking them. 
When importating this to my database with osm2pgsql, it creates  10 rows in the planet_osm_line table, which in turn creates some problem with mapnik rendering for correctly spacing the text labels on the road. 

Is this split normal, and/or is there a way to avoid it? 

Thanks a lot. 

P.S. the osm file I used to test: 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<osm version="0.6" generator="" copyright="OpenStreetMap" attribution="http://www.openstreetmap.org/copyright" license="http://opendatacommons.org/licenses/odbl/1-0/">
<bounds minlat="-90" minlon="-180" maxlat="90" maxlon="180"/>
<node id="623" visible="true" lat="-0.339746" lon="6.000000">
</node>
<node id="626" visible="true" lat="7.789438" lon="2.715955">
</node>
<way id="963" visible="true">
 <nd ref="626"/>
 <nd ref="623"/>
 <tag k="name" v="aaaaaaaaaaaaa" />
</way>
</osm>
```

**Comment by damiendevienne** [comment]
Solved alone, following this answer: 
https://help.openstreetmap.org/questions/40888/osm2pgsql-import-splits-ways-in-table-planet_osm_line
Cheers,

**Comment by pnorman** [comment]
The split is intentional, as long linestrings cause rendering performance problems with the standard Mapnik toolchain. It's worth noting that any style has to be able to cope with roads split at arbitrary places, as this happens for other reasons (lane count changes, relations, speed limits, etc, or sometimes just because).

See also #277, which is probably the route to making this configurable.
