### ISSUE TITLE
Slow going over pending ways...

### ISSUE THREAD

**Issue by leblowl** [openstreetmap/osm2pgsql#517]
Hey All! So I am trying to complete a full planet import on some pretty good hardware. The parsing only takes 7 hours, everything looks good, but then when it gets to going over pending ways, osm2pgsql seems to just get stuck on 'Using 8 helper-processes'. It's been there for about 10 hours. Looking at `top` there appear to be 16 postgresql processes which seems a little odd. I feel a full planet import shouldn't take this long on this hardware as long as I have all my settings dialed in & osm2pgsql is working properly. Any advice as to what might be going on? thank you!

using latest osm2pgsql from github
using this command: `osm2pgsql --create --slim --flat-nodes nodes.bin -C 28000 --number-processes 8 --hstore -S ~/openstreetmap/osm2pgsql/default.style planet-151207.osm.pbf`

**Comment by leblowl** [comment]
psql settings:
```
max_connections = 300 
effective_cache_size = 96GB
shared_buffers = 512MB
work_mem = 1536MB
maintenance_work_mem = 4GB
wal_buffers = 16MB
checkpoint_segments = 1600
checkpoint_completion_target = 0.9
random_page_cost = 1.1
cpu_tuple_cost = 0.05
effective_io_concurrency = 15

fsync = off
full_page_writes = off
synchronous_commit = off

autovacuum = on
autovacuum_vacuum_scale_factor = 0.05
autovacuum_analyze_scale_factor = 0.2

shared_preload_libraries = 'auto_explain'
auto_explain.log_min_duration = '5s'
```

**Comment by uberguru** [comment]
Annoying isn't it, you went nuts bought the biggest baddest server in town, and the the whole thing bottoms out. As someone who has just done serveral planet imports in the past couple of weeks, its takes around 6 days on i7-4770k + 32 gb ram and spinnging disk raid1.  People say use SSD and i agree SSD's are good the main reason is the whole IO seems to be random reads writes hence it just chugs along during certain stages with random postgres processes reading and writing a few measly MB's per second. hardly even a challenge for spinning disk. 

my advice 96GB effective cache is just nuts, postgres is heavly reliant on the cached part of linux memory, better off just allocating that memory to -C flag in the import process.  Helper procsses tend lose effectiveness after 6 threads.  That flat nodes flag is gonna slow you down alot also. 

its old but you can get some good pointers from this slidedeck you can only dial in postgres some much before tweaking makes no difference i.e disabling fsync is pointless, just means you might lose your data. 

http://www.geofabrik.de/media/2012-09-08-osm2pgsql-performance.pdf

Hang in there... its slow but its not stuck it think the major performance factors are single threaded core performance i.e. IPC and clock speed and IOPS and random IO read write spead. i.e. importing on a 48 core server with a 2.4ghz clock vs importing on 3.4 ghz 4 core machine probabbly gonna be better.  I notice the helper processes dont really kick in anyway until going over pending ways. 

Its a black art..... and everyone perform the magic trick differently.

**Comment by pnorman** [comment]
> It's been there for about 10 hours. Looking at `top` there appear to be 16 postgresql processes which seems a little odd. I feel a full planet import shouldn't take this long on this hardware as long

You haven't provided any details about your disk's random IO performance, so it's hard to make any solid comments, but 10h in pending ways is not abnormally slow if you have slower disks.

**Comment by leblowl** [comment]
@uberguru thanks for the advice & positive encouragement. I will look into the source you mentioned & some of the other details regarding best hardware for the job - crazy new world I am in coming from a mainly software background.
@pnorman what information could I provide you with that would help us identify any bottlenecks? any commands I should run? thank you

**Comment by pnorman** [comment]
> @pnorman what information could I provide you with that would help us identify any bottlenecks? any commands I should run? thank you

Standard tools like top, iotop, iostat, htop, etc should all identify what is limiting. Odds are that you're limited by IO speed, but you want to confirm that.

------

> my advice 96GB effective cache is just nuts, postgres is heavly reliant on the cached part of linux memory, better off just allocating that memory to -C flag in the import process. Helper procsses tend lose effectiveness after 6 threads. That flat nodes flag is gonna slow you down alot also.

This is horrible advice. Flat nodes is a big performance increase, 8 processes is faster than 6 (though not 33% faster), cache above about 28GB (num nodes * 8 bytes / efficiency) is pointless, and effective_cache_size is not the memory postgres uses, but an estimate of total memory used for caching.

**Comment by mboeringa** [comment]
> are good the main reason is the whole IO seems to be random reads writes hence it just chugs along during certain stages with **random postgres processes reading and writing a few measly MB's per second.** hardly even a challenge for spinning disk.

If you look at the structure of the OSM XML format (http://wiki.openstreetmap.org/wiki/OSM_XML), you'll quickly realize why importing is such an IO and processor intensive process, with many apparent random read/write actions. Essentially, the full relational hierarchy of relations / ways down to nodes must be traversed and processed to build a single multipolygon relation or way from nodes. It is all stored as the full key/value data from the main database.

Multipolygon and way geometries are **not** "self-contained", they must be build from their respective parts (ways and nodes). This means that for creating a single PostGIS - or other spatial database format - geometry many reads from different parts of a way or node table may be necessary.

That's why, even though the actual "MB/s" IO may seem measly for an average modern hard drive capable of over 180MB/s, it still may be very taxing for the disk. And that probably also explains why SSDs are superior, as not relying on the physical movement to randomly read data.

If the format were different, with geometries self contained and fully resolved, like in a spatial database dump or export, hard drives would probably be a much more viable solution for large imports. Of course, the data *would* be severally inflated...

Anyway, I am using the ArcGIS Editor for OpenStreetMap for all my importing using ArcGIS. Although it does a pretty good job in processing the multipolygon and way data, it is even considerably slower. My Geofabrik DACh - Germany, Austria and Switzerland - import (admittedly against a single harddrive, because I had no SSD big enough to contain the resulting File Geodatabase), took some 2-3 weeks...

**Comment by leblowl** [comment]
So I'm not exactly sure what I am looking for but iostat reads:

```
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
                 5.26      0.00    0.54         3.47       0.00       90.73

Device:            tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
sda            268.89     3351.80   11663.23  460950291 1603967073
```

**Comment by leblowl** [comment]
In top I have 0.0 wa most of the time, sometimes it goes to 0.1 & then up to 1.0 once in a while. My top postgres process however is at 100% cpu...

**Comment by leblowl** [comment]
Ok I think I can actually close this now, thank you for the advice. I will do some more performance testing on various stages of the import. At least I know it is probably hardware related & have some good ideas of what is required for speed with this thing. Cool, thank you!
