### ISSUE TITLE
Multipolygon rendered using tags from outer way

### ISSUE THREAD

**Issue by zeromap** [openstreetmap/osm2pgsql#528]
I was referred to this repository after opening an issue on [OSM Carto](https://github.com/gravitystorm/openstreetmap-carto/issues/2019). 

![hole](https://cloud.githubusercontent.com/assets/15248277/12277203/236d8894-b948-11e5-8d5d-f2dca6cb965f.png)

The geometry of [r5856226](https://www.openstreetmap.org/relation/5856226) is being rendered with the tags of [w186712414](https://www.openstreetmap.org/way/186712414).

Multipolygon relations should be rendered by the tags they have, not by the tags of one of their members, right? building:part is not rendered so this should appear as a solid building since [w186712414](https://www.openstreetmap.org/way/186712414) has the building=yes tag.

This issue is not about 3D mapping, but for reference the building is three levels above ground and the interior is one level above ground. There are also building:part ways 2 and 3 levels above ground, mapped as such.

[F4map 3D](http://demo.f4map.com/#lat=43.0513690&lon=-76.1544447&zoom=20&camera.theta=59.697&camera.phi=-65.604)

![f4map](https://cloud.githubusercontent.com/assets/15248277/12277211/2a1ed8fa-b948-11e5-94bf-2839f7f2f73b.png)

**Comment by pnorman** [comment]
Assuming that you're using default.style, an initial guess is that it's detecting it as an old-style multipolygon as none of the tags on it are in the style file.

**Comment by mboeringa** [comment]
Note that AFAIK osm2pgsql, and a lot of other software, do not (yet) process **type=building** relations in a (specialized) way. Most just interpret any valid multipolygon or closed way with a **building=x** tag as being a building.

Anyway, from a OpenStreetMap "Simple 3D Building" tagging perspective, there are probably a couple of issues with the object as you entered it:

- The **type=building** super-relation (https://www.openstreetmap.org/relation/5857090) that is supposed to tie all building:parts together, is carrying a tag of its own: **building=yes**, which duplicates the building=yes tag on the outline. As far as I can interpret the Simple 3D scheme, it is best not to add any tags to the **type=building** relation itself, but to only add them to the geometry representing the outline of building and using the **role=outline** role as part of the *type=building* super-relation. This is done to make it easier for software that can't or doesn't process super-relations, to still access all details of the building as stored on the outline. Of course, via a properly set part with **role=outline**, software that does have full understanding of all relation levels, can still access all of the same data as well. The **type=building** relation should consequently only be used to tie all parts together.

- The outline way (https://www.openstreetmap.org/relation/5856226) used as **role=outline** correctly has a building=yes tag and name=x tag, but *doesn't* include the inner courts of the building by cutting them from the feature (way set as "inner" for the multipolygon). Although the specification doesn't require it, I would recommend to exclude or cut the area of inner courts of 
https://github.com/openstreetmap/osm2pgsql/issues/528#buildings as part of a multipolygon outline, so as to better represent them as an outline feature. Inner courts can be very big, and not showing them gives a false impression of the true building's size and form or structure. I would suggest to interpret the "outline" more as a "footprint" of the building on ground level, instead of the most outer way.

- The outline way (https://www.openstreetmap.org/relation/5856226), and some other building:part(s), has a **building:min_level=1** tag set. According to this page: http://wiki.openstreetmap.org/wiki/Simple_3D_buildings, the **building:min_level=x** tag specifies how many levels are ***not*** present in a certain building part. I am pretty sure, looking at your F4Map example, you did not intend to have this part of the building to not have a street level storey (which seems unlikely and also not displayed in F4Map)?

**Comment by zeromap** [comment]
@mboeringa The rendering was like that before I created the type=building relation and there was no apparent change in rendering afterwards. Per your advice, I have removed the building=yes tag from the relation (https://www.openstreetmap.org/relation/5857090) though.

It's hard to tell from the image, but what appears to be the inner court of the building is actually the roof of the first story/level above ground. The inner part does not reach ground level. The first floor above ground level covers the entire area of the building expressed as the building=yes way(https://www.openstreetmap.org/way/186712414) The rest of the building:part are on top of that base. Which is why it seems odd for this part (https://www.openstreetmap.org/relation/5856226) to have a building:min_level=1 tag.

**Comment by mboeringa** [comment]
> It's hard to tell from the image, but what appears to be the inner court of the building is actually the roof of the first story/level above ground. The inner part does not reach ground level. The first floor above ground level covers the entire area of the building expressed as the building=yes way(https://www.openstreetmap.org/way/186712414)

OK, that was indeed not immediately apparent from the image or tagging. In that case, your current tagging seems pretty much fine and conform the 3D tagging scheme.

**Comment by mboeringa** [comment]
@zeromap Interestingly, only the Standard and Humanitarian layer show an incorrect building footprint. I think both use a slightly outdated osm2pgsql version, if I understood some remarks from maintainers in the past right. OpenCycleMap, Transport and MapQuest Open do show a filled building polygon without a hole.

I think this issue will be fixed when the database finally gets reloaded and the latest versions of tools installed.
