### ISSUE TITLE
Adding/storing the node's lon and lat as columns in Postgis

### ISSUE THREAD

**Issue by samisnunu** [openstreetmap/osm2pgsql#562]
Hi,
I want to import(store) the node's lon and lat into separate columns in PostGIS.

As long as the.osm xml file has already this info.
even if I use the  -E:4326, --extra-attributes parameters, and set them in the .style file:
node    lat                   		real    linear
node    lon                   		real    linear

to be imported as columns in PostGIS _point table, osm2pgsql will not import them at all.

Please advise,

Thanks
Sami

**Comment by gravitystorm** [comment]
I would advise against doing this. You can use `select st_y(way)` and `select st_x(way)` whenever you need the latitude or longitude.

osm2pgsql has no support for adding latitude or longitude columns, since that would just duplicate the contents of the way column. Adding things to the .style file won't work in any way.
