### ISSUE TITLE
OSM relations and hstore

### ISSUE THREAD

**Issue by settigan** [openstreetmap/osm2pgsql#605]
Hello, I have a question regarding the style file, OSM Relations and the hstore option in osm2pgsql.
I would like to filter my imported data before it gets in my database. For that I use the stylefile and define the tags I would like to keep. I also would like to keep the other tags of the elements which I set in the stylefile thats why I use the hstore option --hstore-match-only. It seems to work for my node table but my line and polygon tables are full with data which I don't need.
Unfortunately it seems as if osm2pgsql pushes all the OSM-Relations in my db wheter there is a connection to my tags in the stylefile or not. 
Is it possible to use a filter function for the relations similar to the filter in the style file? I actually thought the relations would be filtered as well like the nodes and ways.
I also read about the luna file but it seems a little bit complicated so I thought there might be an easier way which I haven't discovered yet. Any help is appreciated.

stylefile
![stylefile](https://cloud.githubusercontent.com/assets/16205332/16828339/ceaebf36-49c9-11e6-86d3-393839ea8d73.png)

Output
![relationproblem](https://cloud.githubusercontent.com/assets/16205332/16828359/f452fcf2-49c9-11e6-8f63-2823084f619b.png)

**Comment by rurseekatze** [comment]
I am having the same problem and discovered this issue. It seems that every relation is imported into the database, even if it has no tag contained in the stylefile.

@settigan Is there any area-Tag in your stylefile? For example this line:

`node,way   area         text         # hard coded support for area=1/yes => polygon is in osm2pgsql`

I discovered that this line affects that every object having an area-Tag is imported into the database. I removed this line and replaced `linear` by `polygon` which causes that every closed way is considered as a polygon, non-closed ways as lines. This was sufficient for my use case. The advantage of this change was that osm2pgsql no longer imported ways without any of the other tags in the stylefile. The only exception were relations, which still seem to ignore the stylefile.

**Comment by lonvia** [comment]
Before discussing the issue in detail, let me say that I wouldn't recommend using the style file for filtering in this way. Have a look at the Lua transform. It gives you much more fine-grained control over tags and filtering.

**Comment by lonvia** [comment]
Here is what happens:  first the tags of the relation are filtered according to your style file. With so few entries, that means that for most relations all tags are filtered away. Next osm2pgsql recognizes a multipolygon and starts handling for it. It finds a relation without tags (because of the filtering) and immediately thinks it is an old-style multipolygon (the tagging style where the tags were out on the member ways, not the relations). So it goes and copies the tags from the first way it finds in the relation. Unfortunately, the way still has its full set of tags because you requested to store all tags in hstore. The result is that a polygon ends up in the database with a completely messed up set of tags.

This is actually closely related to #605 and shows that even for the C transform it is wrong to blindly use the way tag filter for determining multipolygons. How about the following: hand in the original tag list. Then check the non-inners if they have a polygon like tag, if one way is completely without polygon tags, discard completely, otherwise do current handling. @pnorman, any opinion?

**Comment by rurseekatze** [comment]
Thanks for this explaination!

I do not know the exact situation of @settigan, but I want to explain my problem in detail if this might help you or if you know any quick workaround for my problem:

I am using osm2pgsql to import a planet file into a database. I want to import only objects with `railway=*`, also I want to store every tag including `railway=*` in hstore without any own tag column. For importing I am using this command:

`osm2pgsql --create --slim --hstore-all --hstore-match-only --hstore-add-index --style openrailwaymap.style --flat-nodes flatnodes --input-reader pbf planet-latest.osm.pbf` (removed some args such as database connection, which are not relevant here)

My style file looks like this:
```
# OsmType  Tag          DataType     Flags
node,way   z_order      int4         linear # This is calculated during import
way        way_area     real         linear # This is calculated during import
node,way   railway      text         polygon,nocolumn
```

As I described above, I removed the `area` line to avoid that any objects are imported just because of their `area=*`. Now only nodes and ways with `railway=*` are imported, except for relations.

**Comment by pnorman** [comment]
> This is actually closely related to #605 and shows that even for the C transform it is wrong to blindly use the way tag filter for determining multipolygons

Do you mean #659?

**Comment by pnorman** [comment]
I also recommend starting with [empty.style](https://github.com/openstreetmap/osm2pgsql/blob/master/empty.style) for anything very custom.
