### ISSUE TITLE
Run cmake = Psycopg2 error

### ISSUE THREAD

**Issue by Roozaay** [openstreetmap/osm2pgsql#618]
I'm trying to run cmake like it's said in the installation tutorial but i'm getting an error during the regression test : "needs python with psycopg2 module".

I already installed all the needed packages, and psycopg2...

What am I missing ? Thx

**Comment by Noah-Zhang** [comment]
Did you solve the problem? @Roozaay 
I come across the same problem. after I cat the CMakeFileError.log, it seem like that something is wrong with pthread. But I don't know to solve it.

**Comment by lonvia** [comment]
My best guess would be that you've installed psycopg2 for the wrong python version. Use `python --version` to find out what is the default version used in your system and then make sure you've installed the psycopg2 that fits. Most distros come with two versions nowadays, one for python2 and one for python3.

**Comment by Noah-Zhang** [comment]
@lonvia 
My Python version is 2.6.6 and psycopg2 version is psycopg2-2.7.dev()-py2.6-linux-x86_64.egg。Besides, I have tried Python2.7 and face the same problem. 
In Python command line, I can import psycopg2 module without error.

**Comment by lonvia** [comment]
On what system are your compiling? What is your cmake version?

**Comment by Noah-Zhang** [comment]
@lonvia 
CentOS 6.8 && cmake 2.8.12.2

**Comment by Noah-Zhang** [comment]
That issue have been solved. The reason is Boost Version is old.
But when I make the project, it crash again:

/home/git/osm2pgsql/expire-tiles.cpp:53:3: error: looser throw specifier for ‘virtual tile_output_file::~tile_output_file()’
In file included from /home/git/osm2pgsql/expire-tiles.cpp:17:0:
/home/git/osm2pgsql/expire-tiles.hpp:28:17: error:   overriding ‘virtual expire_tiles::tile_output::~tile_output() noexcept (true)’
make[2]: *** [CMakeFiles/osm2pgsql_lib.dir/expire-tiles.cpp.o] 错误 1
make[1]: *** [CMakeFiles/osm2pgsql_lib.dir/all] 错误 2
make: *** [all] 错误 2

**Comment by pnorman** [comment]
If you run `./tests/regression-test.py` does it work?

Also, what is the output for these commands

```
/usr/bin/env python --version
/usr/bin/env python -c 'import psycopg2'
```

**Comment by pnorman** [comment]
Closing with no response from the original reporter
