### ISSUE TITLE
Adding User Defined Columns

### ISSUE THREAD

**Issue by achapkowski** [openstreetmap/osm2pgsql#622]
Is it possible to add a user defined field that may or may not exist in the HStore? 

Let's say I want to load OSM data for a given city X and I want to add a field called HealthCheck to the points table.  If I add this field to the points table, can I still grab the OSM diffs to update the source data?

Is it just an entry to the style file?

Thanks

**Comment by pnorman** [comment]
You can add a column to the tables and it will only be filled in if the tag transform returns a value for that column. If using hstore any tags from the transform without a column in the style file will go into hstore.

You don't want to do this because on update any information you have added will be lost. Instead, create a new table storing OSM ID and your properties and `LEFT JOIN` them together at query time, or something more sophisticated.
