### ISSUE TITLE
Please update the Windows binary downloading URL

### ISSUE THREAD

**Issue by lygstate** [openstreetmap/osm2pgsql#640]
For example:

https://ci.appveyor.com/api/projects/openstreetmap/osm2pgsql/artifacts/osm2pgsql_Release.zip?tag=0.90.1

**Comment by pnorman** [comment]
We don't link to the unofficial binaries directly, do we?

I wasn't aware of the tag query parameter to get the artifact for a particular release from appveyor, but we might be able to link to that. We wouldn't want to link to the readme because it's a version-specific link, but maybe from GH releases somehow?

**Comment by lygstate** [comment]
it's possible for tag and branch

**Comment by pnorman** [comment]
> I think it is fine to link to the current stable version in the README even on master.

I'm not sure how to make a link that always stays to the stable version

**Comment by lygstate** [comment]
There is such a way, to appveyor can specify the tag & branch.

**Comment by pnorman** [comment]
> There is such a way, to appveyor can specify the tag & branch.

How can I specify the latest tag?

**Comment by lygstate** [comment]
latest tag？

**Comment by pnorman** [comment]
The highest versioned tag. It's 0.92.0 right now, but that will change when we release 0.92.1.

**Comment by lonvia** [comment]
I meant to link to the latest stable release number and change that with every major/minor release.

**Comment by lygstate** [comment]
I means add a link to appveyor in GitHub releases
