### ISSUE TITLE
Where is latest build of osm2pgsql for Windows 64-bit

### ISSUE THREAD

**Issue by Koles500** [openstreetmap/osm2pgsql#675]
Hi! 
I am using some earlier build for Windows 64-bit downloaded form here:
https://dl.dropboxusercontent.com/u/63393258/osm2pgsql_testRelease.zip
from this website:
http://awcull.com/2015/09/30/postgis-osm2pgsql-windows.html

but it is crashing when I am importing large pbf with whole Europe downloaded from http://download.geofabrik.de/

I'm tired of this shit... I tried slim and non-slim mode, I tried modifying cache size, nothing worked so far. Our server has 32 GB of RAM.
Where can I download latest osm2pgsql build for Windows 64-bit? Alternatively which compiler do you suggest to make my own build on Windows Server 2012 64-bit. Thanks.

**Comment by Koles500** [comment]
The command I run osm2pgsql last time it crashed was:
`PS C:\OSM\rendering> osm2pgsql -U postgres -m -d osm -p osm -E 3857 -s -S C:\OSM\osm2pgsql\default.style C:\OSM\Data\europe-latest.osm.pbf
`

It crashed with standard Windows dialog saying "the application stopped blablabla" with details:

```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	osm2pgsql.exe
  Application Version:	0.0.0.0
  Application Timestamp:	53ea21fd
  Fault Module Name:	ntdll.dll
  Fault Module Version:	6.3.9600.18438
  Fault Module Timestamp:	57ae642e
  Exception Code:	c00000fd
  Exception Offset:	0000000000030d02
  OS Version:	6.3.9600.2.0.0.272.7
  Locale ID:	1033
  Additional Information 1:	33ad
  Additional Information 2:	33ad00700702b0ab4dc632df7667ec82
  Additional Information 3:	2ebb
  Additional Information 4:	2ebbf5b91303f76c5b7f75f6255100fa

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

```

**Comment by lonvia** [comment]
Try the artifacts from the Appveyor builds. For the latest release: https://ci.appveyor.com/api/buildjobs/iisabxffssilv7gl/artifacts/osm2pgsql_Release.zip

For building osm2pgsql yourself it's probably also best to have a look at the Appveyor config. It uses MSVC 14.0.

See also #640.

**Comment by Koles500** [comment]
Please do not close this yet, I didn't write I am happy with response. I don't quite understand your reply. What are "artifacts"? What is "Appveyor config" and where do I find it?

I downloaded the archive, BUT
Who made that build, is it official?
How do I know that it is latest version? When I run it in console it says version 0.92.0, but Changelog
https://github.com/openstreetmap/osm2pgsql/blob/master/ChangeLog
looks like it has no versions, but only some kind of build numbers.

**Comment by lonvia** [comment]
Appveyor is the continuous integration service we use for testing that osm2pgsql still compiles on Windows. The 'artifact' I was linking to, is the binary that falls out of this testing process. Unfortunately there are no Windows users among the osm2pgsql maintainers, so there is no other testing done on Windows and the Appveyor packages are about as official to a Windows release as it gets. The package I linked to was the built from the last release. If you go to the [main Appveyor page](https://ci.appveyor.com/project/openstreetmap/osm2pgsql/history), you'll also find builds for the newest master version. We certainly would appreciate if somebody would volunteer to look after the Windows build a bit more. the Appveyor config can be found here: https://github.com/openstreetmap/osm2pgsql/blob/master/appveyor.yml  It describes the Testenvironment used by the CI.

I've closed the issue because it is essentially a duplicate of  #640, i.e. asking to document the availability on Windows better. I didn't mean to imply that your issue is not valid.

**Comment by Koles500** [comment]
OK, thank you. I cannot promise that I will do any tests which are not closely related with the project that we work on. All we want is to successfully import Europe PBF or OSM file to database. This tool is running now on our server for few hours already processing Europe data... if it crashes again I will open another issue okay ? ... we need this to be done as soon as possible. Also if it works well I will also inform you.

**Comment by Koles500** [comment]
It is still processing , about 18 hours already. 
`Processing: Node(1827652k 131.7k/s) Way(11431k 0.20k/s) Relation(0 0.00/s)`
Why is it so slow now... only 0.20k/s, it was faster before. Command I used:
`PS C:\OSM\rendering> osm2pgsql -U postgres -m -d osm -p osm -E 3857 -s -S C:\OSM\osm2pgsql\default.style C:\OSM\Data\europe-latest.osm.pbf`

**Comment by Koles500** [comment]
I am a little worried that this may take very long time and who know if this will work at the end or end up with some fucking error. We need this work to be done as soon as possible. It is running in slim mode as I wrote. I had a look into Postgres database in PgAdmin III and I don't see any tables created like osm_nodes nor planet_osm_ways nor planet_osm_rels. Should they be there is place? I clicked "refresh" on "Tables" so I think they should be there... or not ?
