### ISSUE TITLE
Options to import for manual geocoding

### ISSUE THREAD

**Issue by yogeshkumarbalu** [openstreetmap/osm2pgsql#688]
I need to import data for gecoding. I want to do manual geocoding but not with nominatim. 

What are the options to be set because the last time I imported using this command **osm2pgsql -s -U postgres -d gis osm.pbf** and it imported having no **addr:state, addr:city, street, postal code** and other columns. It was hard for geocoding without those columns. 

Please guide me through the process of importing for manual geocoding.

**Comment by pnorman** [comment]
The pgsql backend is intended for rendering. If you want to do geocoding with it you'll need to change the [.style](https://github.com/openstreetmap/osm2pgsql/blob/master/default.style) file you're using to get different tags in. Lua might be helpful here to normalize names (e.g. road contractions)

You can also use the gazetteer backend, which is why nominatim uses. There is little support on its schema.

A third option is to do the import with nominatim but then query the tables manually.
