### ISSUE TITLE
Should we move AppVeyor to VS 2017?

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#775]
AppVeyor now has this available. Are there any downsides to using it?

cc @alex85k

**Comment by lonvia** [comment]
We would need to rebuild all dependencies and I have already forgotten how that works. I also wouldn't drop VS2015 completely but build both instead.

**Comment by mmd-osm** [comment]
Appveyor supports Visual Studio 2019 in the meantime, and the generated binary works on Win10 using Postgres 12.2 libpq.dll: https://ci.appveyor.com/project/mmd-osm/osm2pgsql/builds/34396623/job/jrowhlkfrkrf4uni

(sorry no unit tests this time)

**Comment by lonvia** [comment]
That's good news.

> (sorry no unit tests this time)

Ah, but that's the interesting part. ;) If you don't run the DB tests, then the problematic Postgis binary never comes into play.

If you like to keep working on this (which would be awesome), I think the first step would be to add a build with VS2019 and stay with Postgres 9.6 for testing. (Keep the VS 2015 build. We just don't need to create artefacts for it.) Once that works try again to switch to testing against Postgresql 12/Postgis3. 

Using the psql 11 library instead of 12 was a conscious choice to cover all Postgresql versions osm2pgsql supports (including a couple of ones that are out of official support with Postgresql itself).

**Comment by mmd-osm** [comment]
Appveyor doesn't support Postgres 12 as a service yet (they're still on 10), which further complicates running test cases on 12. https://help.appveyor.com/discussions/problems/25522-postgresql-12 seems to have some good ideas to run your own version.

**Comment by lonvia** [comment]
Right. It is [listed as supported](https://www.appveyor.com/docs/windows-images-software/#databases) but oddly enough is not available. According to [this issue](https://github.com/appveyor/ci/issues/3223) it should be a simple matter of starting it up. Postgresql 11 definitely works, though. That would be fine as well.

We should also consider Github Actions as an alternative. They seem to support Ubuntu, MacOS and Windows. Would be nice to only have to fight against one CI instead of two.

**Comment by mmd-osm** [comment]
I've got a working build on VS2019 and Postgresql12/Postgis 3 now: https://ci.appveyor.com/project/mmd-osm/osm2pgsql/build/job/b2nn6x1qgocpdikw?fullLog=true


```
100% tests passed, 0 tests failed out of 45
Label Time Summary:
NoDB            =   0.25 sec*proc (9 tests)
NoTablespace    = 176.94 sec*proc (42 tests)
Tablespace      =   5.28 sec*proc (2 tests)
Total Test time (real) = 292.71 sec

```

**Comment by lonvia** [comment]
Great, can you make a PR for the version without LuaJIT?

**Comment by mmd-osm** [comment]
Let's do a quick recap of the changes I did in https://github.com/mmd-osm/osm2pgsql/blob/t1/appveyor.yml first:

* environment-gloval:

    - Changed Boost to 1.71
    - Postgis download URL points to osgeo.org 
    - PGGSSENCMODE to work around an issue with Pg12.2 which hasn't been fixed yet. This environment parameter was needed to run `psql -c "CREATE TABLESPACE tablespacetest LOCATION 'c:/temp'"`

* Added matrix build for VS2019

* Removed Services section

* Init section: 
    - Windows Terminal Server + relaxed auth (will not be part of PR)
* Install section:
   - Copy Postgis 3 files while Postgres is not running (otherwise this leads to sharing violation errors)
  - vcvars64.bat resides in another directory
* after_build: 
  - needs proper list of DLLs to include in ZIP
* before_test:
  - Added start up of Postgresql 12
* Test_script:
   - ctest with --output-on-failure option

* on_finish:
   - RDP wait (will not be part of PR)


Do this all make sense?

**Comment by mmd-osm** [comment]
@lonvia : unfortunately my previous post hasn't received much feedback. Is this still relevant today?

**Comment by lonvia** [comment]
Yes, it is still relevant. The changes look mostly good, please make a PR. I'd still like to see postgis downloaded from the osm2pgsql site, so I've added https://osm2pgsql.org/ci/winbuild/postgis-bundle-pg96-2.5.3x64.zip for you to use. If you need a different bundle by now, just let me know.

**Comment by mmd-osm** [comment]
The other bundle the script depends on is https://download.osgeo.org/postgis/windows/pg12/archive/postgis-bundle-pg12-3.0.3x64.zip - just ping me once it's available on osm2pgsql.org, and I'll update the link in #1391.

**Comment by lonvia** [comment]
Should be available now as http://osm2pgsql.org/ci/winbuild/postgis-bundle-pg12-3.0.3x64.zip

**Comment by mmd-osm** [comment]
Thanks! I have updated the link now,

**Comment by joto** [comment]
We are not using Appveyor any more, so this is out of date. Closing.
