### ISSUE TITLE
Clipping in mercator conversion

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/osm2pgsql#793]
The internal osm2pgsql function for conversion for mercator has a hard clipping at 85.07, see https://github.com/openstreetmap/osm2pgsql/blob/master/reprojection.cpp#L23. This is the reason why there are so many invalid polygons near the poles (see #787). We are currently using the exact algorithm for reprojection which degenerates only very close to the pole and PostGIS is quite happy with geometries that are outside the defined area for the projection. Therefore it should be safe to increase the clipping to something much closer to 90 degrees. This way we should be able to obtain valid geometries for most of the OSM objects close to the pole.

We could also switch to libosmium's projection function. It uses a much faster algorithm in the well-defined ranges and degenerates to the exact algorithm when closer to 90 degrees. However, this should be done on top of our choice of clipping. Libosmium itself does not do any clipping at all.

CC @imagico, @joto

**Comment by imagico** [comment]
Just a small note - since this is a frequent misconception:  The Mercator projection (EPSG:3857) is defined for all points except the poles, so also beyond 85.051 degree latitude.  The 85.051 degree limit is just the choice for map rendering to have a square map.

The chosen method to clip very close to the pole instead of immediately beyond the map limit is a good solution IMO (see https://github.com/openstreetmap/osm2pgsql/issues/787#issuecomment-334089478).
