### ISSUE TITLE
Loading data to postgre database too slow

### ISSUE THREAD

**Issue by BranZhang** [openstreetmap/osm2pgsql#798]
I am trying loading an osm data(about 37GB) to my local postgreSQL database.
But 2 days past, I found that loading speed slowed down.

**now speed**:Processing: Node(4146299k 17.1k/s) Way(15447k 0.09k/s) Relation(0 0.00/s)
**my script**:osm2pgsql --create --database gis_osm --username postgres --password 
--style C:\Downloads\default.style --slim --cache 5000 C:\Downloads\planet-latest.osm.pbf
**version**: 0.92.0 (64 bit id space)

should I restart this and change some parameters?

**Comment by StyXman** [comment]
I the DB resides on a HDD instead of an SSD or something faster, the import is going to be *slow*. A couple of years back I tried to import Europe (~16 GiB I think) and I got tired after 2 *weeks*.

**Comment by 1n4001** [comment]
I rent instances on Amazon EC2 for my planet imports and rsync the postgres /var/lib/pgsql contents to a local server with the same OS and Postgres version, but due to a bug in osm2pgsql at the moment I'm importing the individual continent extracts from download.geofabrik.de

Current Europe is 20gb PBF, I may have to --slim that one
