### ISSUE TITLE
Not importing all relations to polygons table

### ISSUE THREAD

**Issue by bartgras** [openstreetmap/osm2pgsql#818]
I have 2 relations which have similar structure but only one of them is being imported into ```planet_osm_polygons``` table. 

The one that is being imported: https://gist.github.com/anonymous/9e12170b7154690874f0a2395e6c91ff
(on OSM it's: https://www.openstreetmap.org/relation/540011)

The one that isn't: https://gist.github.com/anonymous/7cf7c3aa1515e7a5fe0ae57d307dc96c
(on OSM it's: https://www.openstreetmap.org/relation/1206310 )

I've also checked if it somehow wasn't imported into other ```planet_osm_*``` tables.

I've tried importing both with/without ```--multi-geometry``` option.

Both of them are in ```planet_osm_rels``` table:

tags_as_text|id|way_off|rel_off|parts|members|tags
--|--|--|--|--|--|--
{ele,75,name,"Lake Ontario",name:be,"Возера Антарыа",name:cs,"Ontarijské jezero",name:de,Ontariosee,name:es,"Lago Ontario",name:fr,"Lac Ontario",name:hu,Ontarió-tó,name:pl,"Jezioro Ontario",name:ru,"озеро Онтарио",name:sk,"Ontárijské jazero",name:te,"ఒన్ టారియో",natural,water,note,"If editing please make sure outer is intact and all islands are inner",salt,no,source,"CanVec 6.0 - NRCan",sqkm,19011,type,multipolygon,water,lake,wikidata,Q1062,wikipedia,"en:Lake Ontario"}|1206310|0|892|[_int8]|[_text]|[_text]
{attribution,"Natural Resources Canada",canvec:CODE,1480272,name,"Lake Le Barge",natural,water,type,multipolygon,water,lake}|540011|0|2|[_int8]|[_text]|[_text]

And imported one (with some columns skipped) in ```planet_osm_polygon``` looks like this:

osm_id|way_area|tags|way
--|--|--|--
-540011|10460.400390625|[hstore]|[geometry]

Anyone can advise what I might be doing wrong?

**Comment by Unigoge** [comment]
I have the same problem with 0.94 release and these polygons:

this relation - http://www.openstreetmap.org/relation/227303
and this way - https://www.openstreetmap.org/way/169626373

are not getting imported properly...

Switching back to release 0.92.1 has solved the problem.

**Comment by lonvia** [comment]
These two polygons are broken. osm2pgsql does not fix broken polygons any more. This is intentional. You can use the area layer in the OSM inspector to find the error and fix it in OSM directly.

For relation 227303: http://tools.geofabrik.de/osmi/?view=areas&lon=-74.34147&lat=40.98797&zoom=17
For way 169626373: http://tools.geofabrik.de/osmi/?view=areas&lon=-73.96624&lat=40.80451&zoom=18

The original relation from the report shows up as ok in OSMI but I suspect that it simply has been fixed in the meantime. It does import ok for me now.
