### ISSUE TITLE
--expire-tiles: Parameter parsing does not work

### ISSUE THREAD

**Issue by koefmatt** [openstreetmap/osm2pgsql#830]
After upgrading from Debian Stretch (0.92) to Buster (0.94) our update script stopped working. I have tried many styles of passing the `--expire-tiles` parameter with no luck.
The code parsing this parameter was changed significantly in 24488bfdaec2c432e33144ecb2688387253db37c, breaking existing functionality. The command `osm2pgsql -d gis -H localhost -U gisuser -S ~/osm2pgsql/default.style -P 5432 -s -C 800 -a diffs.osc.gz -e15 -o expire.list`, suggested by the OSM Wiki, no longer works.    

What I have tried so far:
  - `-e19`
  - `-e0-19`
  - `-e 19`
  - `-e "19"`
  - `--expire-tiles 19`
  - `--expire-tiles 0-19`
  - `--expire-tiles "19"`
  - `--expire-tiles "0-19"`
  - `--expire-tiles "just work pls"`

When supplying only the max zoom level, I get "_ERROR: Minimum and maximum zoom level for tile expiry must be separated by '-'._" Supplying both min and max yields "_ERROR: Missing zoom level for tile expiry._" Negative zoom levels actually get caught and throw an error.

Is this a user error on my side or is this option actually broken?

**Comment by pnorman** [comment]
cc @Nakaner

**Comment by Nakaner** [comment]
Thank you for your bug report.

The bug described here is partially a bug and partially a missing piece of documentation.

The mentioned commit changed all zoom levels to `uint32_t`. `0` is now reserved for "invalid" zoom level (and `std::strtoul` returns 0 if no integer could be read). Having a tile expiry starting at zoom level `0` will always write `0/0/0` to the expiry list except if the diff to be imported was empty or contained only changes you are not interested in (defined by the style file and/or your Lua filters).

However, my code contained a real bug because it did not accept `-e 19`.

**Comment by koefmatt** [comment]
Brilliant! Thank you.
