### ISSUE TITLE
Osm2pgsql ERROR: Cannot detect file format

### ISSUE THREAD

**Issue by PatriceKast** [openstreetmap/osm2pgsql#856]
Hi there

By trying to import the whole planet (a .pbf file) into a pgsql dataabse on a RedHat Server, I am getting the following error:

`[root@asl-test]# osm2pgsql –s –U postgres –d gis /opt/transfer/planet-latest.osm.pbf 
osm2pgsql version 0.92.0 (64 bit id space) 

Using built-in tag processing pipeline 
Using projection SRS 3857 (Spherical Mercator) 
Setting up table: planet_osm_point 
Setting up table: planet_osm_line 
Setting up table: planet_osm_polygon 
Setting up table: planet_osm_roads 
Allocating memory for dense node cache 
Allocating dense node cache in one big chunk 
Allocating memory for sparse node cache 
Sharing dense sparse 
Node-cache: cache=800MB, maxblocks=12800*65536, allocation method=3 
Mid: Ram, scale=100 

Reading in file: –s 
node cache: stored: 0(-nan%), storage efficiency: -nan% (dense blocks: 0, sparse nodes: 0), hit rate: -nan% 
Osm2pgsql failed due to ERROR: Cannot detect file format. Try using -r. `

I installed all required packages:
`sudo yum install cmake make gcc-c++ boost-devel expat-devel zlib-devel \
  bzip2-devel postgresql-devel proj-devel proj-epsg lua-devel`

Does this error sounds familiar to anyone?

**Comment by woodpeck** [comment]
Does the md5 sum of your planet-latest.osm.pbf match that published on the planet site?

**Comment by lonvia** [comment]
The suspicious part of the output is this one:

    Reading in file: –s

`osm2pgsql` does not recognize the option as an option but interprets it as a fie name instead. My guess would be that you have defined an alias for osm2pgsql in your shell or have a script somewhere with that name that does strange things.

Another possibility: the hyphen is not an hyphen. That can happen when you copy instructions from a website that use m-dashes or the like instead of a simple ASCII hyphen. Retype the line by hand in that case.

**Comment by PatriceKast** [comment]
Thank you! After defining an alias for osm2pgsql in the shell console it worked.
