### ISSUE TITLE
Unofficial Binaries 64bit Windows

### ISSUE THREAD

**Issue by code-beans** [openstreetmap/osm2pgsql#888]
I am looking for the unofficial 64bit Windows binaries. 
The AppVeyor [link](https://appveyorcidata.blob.core.windows.net/openstreetmap-14528/osm2pgsql/0-0-551/np3ini4wgphakjrd/osm2pgsql_Release_x64.zip?sv=2015-12-11&sr=c&sig=6vzcNM4kZIM7CbiwoP3RHWH1IJka9lne5%2BJX2v%2FUR6I%3D&st=2018-12-12T13%3A30%3A14Z&se=2018-12-12T13%3A36%3A14Z&sp=r) seems to be broken/serve empty .zip files.

Did I miss something plain obvious here? I'd like to avoid building from source if possible.

Thanks

**Comment by Nakaner** [comment]
I don't see what your issue is.

Windows binaries are generated by AppVeyor automatically. For example, the link to the build of the latest commit to the master branch: https://ci.appveyor.com/project/openstreetmap/osm2pgsql/build/job/p6je00k7v6al8j8w/artifacts

However, builds of old commits (e.g. latest release 0.96.0) are not available any more. https://ci.appveyor.com/project/openstreetmap/osm2pgsql/build/0.0.551/job/np3ini4wgphakjrd/artifacts writes:
>  Artifacts older than 6 months are automatically deleted. For more details see [Artifacts retention policy](https://www.appveyor.com/docs/packaging-artifacts/#artifacts-retention-policy).

**Comment by code-beans** [comment]
Oh I see.  I am unfamiliar with AppVeyor and did not see the artifacts tab under _arch=x64_ and just assumed there would be something like a _windows=x64_ job.

Solved and closed. Thanks for the quick response.
