### ISSUE TITLE
Change of index names

### ISSUE THREAD

**Issue by NopMap** [openstreetmap/osm2pgsql#912]
I am importing data in the background and need to rename tables and indexes after import is complete.

i am getting errors trying to rename the indexes when switching between release 0.96 and master.

Was there a change of the index naming recently?
If not, is there another dynamic involved with creating the names for the main GIST indexes?

**Comment by mmd-osm** [comment]
Probably this pull request is relevant here: https://github.com/openstreetmap/osm2pgsql/pull/848

**Comment by NopMap** [comment]
Yes, this seems to be the culprit.

Looking into the code, I seems that there is no name given for the index at all now.

So where does the actual name come from? 
Some sort of default behaviour? 
Is this documented anywhere? 
Is it dynamic, does it change depending on the version of the Postgres DB for example?

**Comment by thbeutin** [comment]
[...]
> So where does the actual name come from?
> Some sort of default behaviour?
> Is this documented anywhere?

It's a postgresql default behaviour documented in their docs:

https://www.postgresql.org/docs/11/sql-createindex.html


> Is it dynamic, can it change depending on the version of the Postgres DB for example?

if you check the history of the documentation you'll see the first appearance for an optional name argument in v9.0, and the doc didn't changed since then. But the meaning of "If the name is omitted, PostgreSQL chooses a suitable name based on the parent table's name and the indexed column name(s)." might change over time ;)
