### ISSUE TITLE
Move to C++14

### ISSUE THREAD

**Issue by pnorman** [openstreetmap/osm2pgsql#950]
C++14 is now 5 years old. We should move to it after reviewing compiler support.

**Comment by mmd-osm** [comment]
To take advantage of new C+11 or even C++14 features, one first step could be to carefully review  recommendations made by clang tidy modernize. This may require several iterations, as some of the proposed changes trigger further recommendations.

`clang-tidy -checks="modernize-*" *.cpp *.hpp -- -std=c++14 -Ibuild -I/usr/include/postgresql/ -I/usr/include/lua5.2/`

**Comment by joto** [comment]
C++14 doesn't really bring that many advantages. You, there is a `make_unique`, some constexpr and lambda improvements etc. but I don't see any major advantages for us. So unless we need to switch anyway because some library we use needs it or so, I'd leave it as it is. We still have enough C->C++ and C++98->C++11 cleanups we can do.

What will be a major change is to C++17, which brings, for instance, `std::variant` and other useful stuff. So I would suggest we target that at some point in the future.
