### ISSUE TITLE
upgrading osm2pgsql

### ISSUE THREAD

**Issue by thewildman** [openstreetmap/osm2pgsql#951]
The 0.94.0 release notes states that "Upgrading to this version requires a reimport for the slim
table changes"

Will it then be enough to use the flat-nodes file from a 0.96.0 import to upgrade a 0.93.0 import to 0.96.0 (or even 1.0.0) ? Considering that both are updated to the exact same osm state, of course.

I have not found structure differences between my server updated using 0.96.0 and my server being updated using 0.93.0 (dev), so I though I might benefit from the new features in 0.96.0 and up by simply replacing the flat-nodes file from the 0.96.0 import and replacing the osm2pgsql binary.

Is this correct ?

**Comment by lonvia** [comment]
I don't think we've had any changes to the database layout, so it should be okay to do that. Personally, I'd wind back the updates a bit, to be sure that you are really in sync. That means whatever date you think your new flatnode file contains, go a day or two back and use the OSM state file for that. Then restart updates. This is always safe to do. (Meaning that you can use any 0.96 flatnode file that is older than your 0.93 flatnode file.) Once you've reached the original date, your database will be in a consistent state again. You might find some minor oddities in rendering afterwards because the way we build geometry areas has changed significantly in 0.94 but I would expect it to be more of an aesthetic problem, nothing serious.

The official disclaimer to this is of course: we give no guarantees that doing this won't lock up your computer, destroy your database and leave you wanting to change your profession.

**Comment by thewildman** [comment]
OK, that's very good news !
Indeed, going back some days might be a good idea. The problem is that the server that is lagging behind some versions of osm2pgsql is quite slow, and it takes hour for it to apply a daily update (it can apply around 3 daily updates in a day). So I don't want to go to far back to avoid overloading it afterwards.

Thanks for the advices ! I think the terms of the disclaimer are fair ! ;)
