### ISSUE TITLE
Question: Changing table names in .style

### ISSUE THREAD

**Issue by merspieler** [openstreetmap/osm2pgsql#958]
I'm trying to import the data for a progam that expects different table names than the ones created by osm2pgsql. Currently I do the import with osmosis tho I'd like to replace it with osm2pgsql. Mainly to be able to update the db without complete reimporting the entire world.

How the names should look like:
```
gclp=> \d
 Schema |       Name        |   Typ   | Owner
--------+-------------------+---------+------------
 public | geography_columns | Sicht   | postgres
 public | geometry_columns  | Sicht   | postgres
 public | nodes             | Tabelle | myuser
 public | raster_columns    | Sicht   | postgres
 public | raster_overviews  | Sicht   | postgres
 public | relation_members  | Tabelle | myuser
 public | relations         | Tabelle | myuser
 public | schema_info       | Tabelle | myuser
 public | spatial_ref_sys   | Tabelle | postgres
 public | users             | Tabelle | myuser
 public | way_nodes         | Tabelle | myuser
 public | ways              | Tabelle | myuser
```

Is there a way to define the table names in a .styles file?

**Comment by mmd-osm** [comment]
One issue I see is that osm2pgsql uses a completely different table structure than what you have in your current osmosis db (it seems you're currently using a pgsnapshot schema?).

So my first question would be what your use case is, and why you want to switch to osm2pgsql in the first place.

Otherwise you could of course to define some SQL VIEWs instead, which fetch data from the original tables without reloading. But as I said, that probably won't work out of the box due to the large differences between those two schemas.

**Comment by lonvia** [comment]
The database schemas of osmosis and osm2pgsql are not compatible. VIEWs will not really help in this situation. If you are mainly after updates, then [osmosis can do that for you](https://wiki.openstreetmap.org/wiki/Osmosis/Detailed_Usage_0.47#--write-pgsql-change_.28--wpc.29) with your existing database.

On a general note: this is more a question for the [mailing list](https://lists.openstreetmap.org/listinfo/dev) as it would help to understand better what you have and what you are trying to achieve.

**Comment by merspieler** [comment]
Okay, then I'll stick with osmosis for now... (and maybe talk to the author of the sw i'm using the db with to support the osm2pgsql schema)

Thank you
